version: "3"
services:
  nginx:
    image: panmourovaty/dockered-nginx
    ports:
     - 80:80
     - 443:443
    volumes:
      - ./conf:/etc/nginx/conf.d
      - ./certs:/opt/certs
      - ./www:/var/www
      - ./logs:/logs
